//punctuation
var arr_punctuation:Array = new Array("...", "...", "...", ".", ".", ".", "!", "?", "!?", "??");
//
var arr_potato_click:Array = new Array("Zines are pretty great! I hope this tool helps.", "Please make a zine about a potato! Thank u!", "I'm so happy to be part of your creative process!", "I'm just happy to be here and be able to share in the creative process.", "Thank you for letting me help!", "I'm a good potato!", "I have a lot of respect for DIY artists. It's so cool to be part of this!", "I love DIY art things. Zines are so cool.", "Zines are awesome! Yay!", "I love zines.", "I love zines, although I'm not 100% certain how to pronounce the word. It's kinda too late to ask. It would be awkward.", "How do you pronounce zine anyway...?", "alienmelon made this tool because they really wanted something like MS Paint but for zines.", "How are you? I'm doing great! I'm a potato helper!", "I'm not really an Electric Love Potato yet. I'm volunteering in this software to earn my stripes so I can be one!", "I'm volunteering being a potato assistant in this zine tool so I can earn my stripes and become a full fledged Electric Love Potato.", "OH MY GOD I LOVE ZINES!", "I LOVE ZINES!", "Hey! You're pretty great!", "Haha! That tickles!", "You're so talented, oh my god!", "Hey! Draw me!!!", "Draw me! Draw me!!", "Ha! That tickles! OMG!", "omg draw me! Draw me! Yay!", "Whenever I have writers block I think of potatoes and that always inspires me. I'm a potato. I inspire myself!", "I'm a potato! One of the best!", "I'm a potato assistant. I'm one of the best! Ha!", "Haha!", "Oh!", "Oh haha!", "Yay!", "I'm so happy!", "I love zines! Yes!", "I love zines! No doubt! Yup!", "Writers block is all part of the creative process. No worries if you're having it! Just believe in yourself!", "Just believe in yourself and your creative process. You'll do great!", "You'll do great! Just make art and put yourself out there!", "Zines are fun!", "Yay! I love zines! I love being here!", "I love being here! Thank you for using this program!", "Yay! Thank you for using this program! It keeps me employed.", "I'm employed right now because you're running this program, so thank you for that. I love this job!", "I love this job! I love being a potato assistant. I give the best tool-tips! Yup!!", "Yay! I'm happy!", "Yay! I'm so happy to be part of the creative process! You have no idea...", "alienmelon loves UI work. As you can tell. They really got into the colors with this one.", "Haha! omg that tickles!", "Yay! I love being clicked! Clicks actually tickle. Haha!", "Omg haha! Mouse clicks tickle!");
//print messages
var arr_printMsg:Array = new Array("Printing a zine!", "Printing a zine!", "Printing a zine :)", "A zine is printing, yay!", "Yay! Zine incoming!", "Yay! A zine is printing!", "Your zine is printing :D", "A tiny zine is being printed!", "Yay! Here comes your zine!", "Your zine is being printed :D", "Printing a tiny zine!", "Printing a zine! :D", "Zine printing! :)", "Yay! A zine is printing. :)");
//fanzine tagline
var arr_fanzineline:Array = new Array("What's it take to graduate from 'fanzine' to 'zine', you ask? This tool will help!", "Authenticity ensures that you graduate from 'fanzine' to 'zine'!", "Authenticity is the difference between an ordinary 'fanzine' and a legit 'zine'!", "Authenticity is the difference between a regular 'fanzine' and an actual 'zine'.", "The Authenticity tool will ensure that you graduate from 'fanzine' to 'zine'!", "Tired of telling them that it's a 'zine' and not 'fanzine'? Add authenticity!");
//invisible creature
var arr_invisibleCreature:Array = new Array("\n\n\n..(-.-)..", "\n\n\n..(-.-)..", "\n\n\n..(-.-)..", "\n\n\n..(-.-)..", "\n\n\n..(-.-)..", "\n\n\n..(-.-)..", "\n\n\n..(-_-)..", "\n\n\n..(-_-)..", "\n\n\n..(-_-)..", "\n\n\n..(-_-)..", "\n\n\n..(-_-)..", "\n\n\n..(-_-)..",  ":o hey! this is my secret space!", "an invisible creature occupies this space!", "shhh! an invisible creature is napping here!", "oh hey! i am an invisible creature. this is my home.", "something is hiding behind this UI. it looks invisible.", "something invisible is hiding here!", ":D", ":)", ":p", ":0", ":o", ":|", "*growl*", "*giggles*", "uh oh!", "haha!", "oh hey!", "hey!", "hi!");
//dotted line compliments
var arr_dottedLines:Array = new Array("This tool is made possible because of virtual ants.", "Release the virtual ants!", "Hey! You're doing great!", "You're doing so good!", "I LOVE your art.", "You're such a good artist.", "Good job!", "Yes. Love what you're doing.", "The digital ants make these lines possible.", "Haha, that tickles!", "Hey! You're cool.", "I like your stuff.", "Nice work. Very nice. Yes.", "I like your zines :3", ":3 hey~", "I love your work :3", "Looking good!", "This zine is going to be so good...", "This zine is going to be great!", "lol this zine is going to be so good!", "Yes. Good job zine making!", "Excellent zine making skills!", "These are some excellent zine making skills.", "Impressive zine making prowess, yes.", "Nice!", "Yay!", ":3", ":3", ";3", "I like your work :3", "I like your art :3");
//VOID
var arr_void:Array = new Array("the void is pleased with your cries. it rewards you with great art", "the void consumes your art. it is pleased", "the void consumes your art", "ah yes, the torment of artistic authenticity", "the void embraces your screams and rewards you with great art", "the void rewards you with great art. you are heard", "the void rewards your tormented genius with great art", "ah yes, the cold brutal torment of the artistic genius", "you feel validated", "you feel understood", "you feel less frustrated", "ah yes... that was good", "at last! you feel understood", "yes... you feel validated", "you feel so validated right now", "such validation", "the void hears you... great art comes with great validation", "ah yes, you feel less consumed by the passion to create great art", "such great art", "as your screams echo back, you feel validated by the resulting art", "you feel validated by the resulting art. it was worth it", "you feel validated. it was worth it. such great art");
//the void ____ you
var arr_void_actions:Array = new Array("validates", "hears", "acknowledges", "understands", "takes note of", "ignores", "is indignant towards", "receives", "gets", "gets", "knows", "appreciates", "notices", "recognizes", "approves of", "certifies", "justifies", "legitimizes", "verifies", "approves of", "approves");
//skeleton facts (for the ascii tool)
var arr_skeleton_didyouknow: Array = new Array("Did you know? Skeletons hold your body together. Without them you would be a puddle!", "Did you know? Without skeletons there would be no people!", "Did you know? Skeletons keep us from being people puddles. Please thank your skeleton!", "Did you know? Skeletons are awesome, and everybody has one!", "Did you know? There is a skeleton hiding in your body just waiting to pop out!", "Did you know? One day all skeletons plan on popping out of their human hosts at the same time!", "Did you know? Without your skeleton you would collapse in on yourself!", "Did you know? Skeletons are pretty awesome and very necessary.", "Did you know? Before skeletons where invented humans where actually slugs!", "Did you know? Humanity invented skeletons to keep them from being gross people puddles!", "Skeletons always look like they are smiling because they are happy about being dead!", "Did you know? If you had no skeleton you would implode on yourself! That would be gross!", "Did you know? Without your skeleton you would be a disgusting mess. You are welcome!", "Did you know? Slugs don't have skeletons. Without your skeleton you would be a slug. Gross!", "Did you know? Skeletons keep humanity from being gross. Without them you would be a slug!", "Did you know? Skeletons can be used to make a broth after they are no longer used.", "Did you know? A skeletons primary function is to prop up your body. You are welcome!", "Did you know? A skeleton is basically the framework of your body. Humans need us!", "Did you know? A skeleton is a pretty awesome thing and you should appreciate us!", "Did you know? Skeletons can break, but we heal too. We are self-sustaining!", "Did you know? Without their skeletons humanity would be a weird gross pile of skin!");
//compliments in the PAINT AND FILL tool
var arr_paintandfill_compliments:Array = new Array("Hey! You're pretty lovely!", "You're doing great!", "I love your style :)", "You're pretty cool!", "Hey! You're nice!", "Hey! I like you! :)", "You're doing great! :D", "You got this! :)", "You can do it! :D", "Hey! You're pretty great!", "Yay! You're doing it!", "Yay! You go!", "Look at you go! :D", "Yay! So cool!!", "Woohoo!", "Hello :)", "Oh hey :D", "Yay!");


function rand_array(arr:Array){
	return arr[Math.ceil(Math.random()*arr.length)-1];
};